"""Constants for PostgreSQL management operations."""

class PostgresConstants:
    """Centralized constants for PostgreSQL operations."""
    
    # Default paths
    DEFAULT_POSTGRES_PATHS = {
        'debian': {
            'config_dirs': ['/etc/postgresql', '/var/lib/postgresql'],
            'data_dirs': ['/var/lib/postgresql'],
            'service_name': 'postgresql'
        },
        'rhel': {
            'config_dirs': ['/var/lib/pgsql'],
            'data_dirs': ['/var/lib/pgsql'],
            'service_name': 'postgresql'
        }
    }
    
    # Configuration file names
    CONFIG_FILES = {
        'postgresql_conf': 'postgresql.conf',
        'pg_hba_conf': 'pg_hba.conf',
        'pgbackrest_conf': 'pgbackrest.conf'
    }
    
    # pgBackRest configuration
    PGBACKREST = {
        'config_dir': '/etc/pgbackrest',
        'conf_d_dir': '/etc/pgbackrest/conf.d',
        'log_dir': '/var/log/pgbackrest',
        'backup_dir': '/var/lib/pgbackrest',
        'default_retention_full': '2',
        'default_retention_diff': '3',
        'max_backups_before_full': 10
    }
    
    # Timeouts and retries
    TIMEOUTS = {
        'command_timeout': 300,
        'service_start_timeout': 60,
        'backup_timeout': 3600,
        'restore_timeout': 7200
    }
    
    RETRIES = {
        'max_retries': 3,
        'retry_delay': 5,
        'service_start_retries': 5
    }
    
    # PostgreSQL settings
    POSTGRES_SETTINGS = {
        'listen_addresses': "'*'",
        'archive_mode': 'on',
        'wal_level': 'replica',
        'max_wal_senders': '3',
        'archive_timeout': '60'
    }
    
    # Default pg_hba.conf content
    DEFAULT_PG_HBA_CONTENT = """# Generated by NexPostgres
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Database administrative login by Unix domain socket
local   all             postgres                                peer

# "local" is for Unix domain socket connections only
local   all             all                                     md5

# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv4 external connections:
host    all             all             0.0.0.0/0               md5

# IPv6 local connections:
host    all             all             ::1/128                 md5
# IPv6 external connections:
host    all             all             ::/0                    md5
"""
    
    # OS detection patterns
    OS_PATTERNS = {
        'debian': ['ubuntu', 'debian'],
        'rhel': ['centos', 'rhel', 'red hat', 'fedora', 'rocky', 'alma']
    }
    
    # Common PostgreSQL commands
    POSTGRES_COMMANDS = {
        'version_check': 'psql --version',
        'service_status': 'systemctl status postgresql',
        'service_start': 'systemctl start postgresql',
        'service_stop': 'systemctl stop postgresql',
        'service_restart': 'systemctl restart postgresql',
        'reload_config': 'systemctl reload postgresql'
    }
    
    # Package names by OS
    PACKAGE_NAMES = {
        'debian': {
            'postgresql': 'postgresql',
            'postgresql_contrib': 'postgresql-contrib',
            'pgbackrest': 'pgbackrest'
        },
        'rhel': {
            'postgresql': 'postgresql-server',
            'postgresql_contrib': 'postgresql-contrib',
            'pgbackrest': 'pgbackrest'
        }
    }
    
    # Error messages
    ERROR_MESSAGES = {
        'postgres_not_installed': 'PostgreSQL is not installed on the server',
        'config_file_not_found': 'Could not locate PostgreSQL configuration file',
        'backup_failed': 'Backup operation failed',
        'restore_failed': 'Restore operation failed',
        'service_start_failed': 'Failed to start PostgreSQL service'
    }